### ISSUE TITLE
What is the peer name If we add two member  

### ISSUE THREAD

**Issue by guru260** [aws-samples/non-profit-blockchain#109]
I set up hyperledger fabric network using single member in amazon manged blockchain. I have used [this rest api](https://github.com/aws-samples/non-profit-blockchain/tree/master/ngo-rest-api). It worked properly. Then I added one more member follwoing [this document](https://docs.aws.amazon.com/managed-blockchain/latest/managementguide/get-started-joint-channel.html). I have added endorsement policy as below,
```
docker exec cli peer chaincode instantiate -o $ORDERER \ 
-C ourchannel -n myjointcc -v v0 \
-c '{"Args":["init","a","100","b","200"]}' \
--cafile /opt/home/managedblockchain-tls-chain.pem --tls \
-P "AND ('Member1ID.member','Member2ID.member')"
``` 
Now I need to add peer of new member in [this config file](https://github.com/aws-samples/non-profit-blockchain/blob/master/ngo-rest-api/config.json) I have added like `"peers":["peer1", "peer2"]`. But I am getting the following error in REST Server.
```
[2020-09-02 05:54:20.915] [ERROR] invoke-chaincode - Error: Peer with name "peer2" not assigned to this channel
    at Channel._getTargets (/var/www/html/network/node_modules/fabric-client/lib/Channel.js:3515:13)
    at Channel.sendTransactionProposal (/var/www/html/network/node_modules/fabric-client/lib/Channel.js:2791:26)
    at Object.invokeChaincode (/var/www/html/network/app/invoke-transaction.js:41:31)
    at <anonymous>
[2020-09-02 05:54:20.915] [ERROR] invoke-chaincode - Failed to invoke chaincode. cause:Error: Peer with name "peer2" not assigned to this channel
```
Help me what peer name should I use here for peer of newly added member.

**Comment by MCLDG** [comment]
@guru260 , the peer needs to be defined in the connection profile: https://github.com/aws-samples/non-profit-blockchain/blob/master/ngo-rest-api/connection-profile/ngo-connection-profile-template.yaml
