### ISSUE TITLE
Can not link to Hyperledger explorer

### ISSUE THREAD

**Issue by Nizomjon1994** [aws-samples/non-profit-blockchain#117]

**Comment by Nizomjon1994** [comment]
I am trying to link AWS managed blockchain with Hyperledger Explorer (https://github.com/hyperledger/blockchain-explorer)

I am getting error while connection to CA_ENDPOINT 


Failed to enroll admin, error:%o message=Calling enroll endpoint failed with error [Error: getaddrinfo ENOTFOUND ca.m-rphxyxdr2zeqljyk6aev5d5txm.n-dzlj7f7bpzed7kwkyi6sdlofxa.managedblockchain.us-east-1.amazonaws.com ca.m-rphxyxdr2zeqljyk6aev5d5txm.n-dzlj7f7bpzed7kwkyi6sdlofxa.managedblockchain.us-east-1.amazonaws.com:30002], stack=Error: Calling enroll endpoint failed with error [Error: getaddrinfo ENOTFOUND ca.m-rphxyxdr2zeqljyk6aev5d5txm.n-dzlj7f7bpzed7kwkyi6sdlofxa.managedblockchain.us-east-1.amazonaws.com ca.m-rphxyxdr2zeqljyk6aev5d5txm.n-dzlj7f7bpzed7kwkyi6sdlofxa.managedblockchain.us-east-1.amazonaws.com:30002]
    at ClientRequest.request.on (/home/explorer/test/node_modules/fabric-ca-client/lib/FabricCAClient.js:327:19)
    at ClientRequest.emit (events.js:198:13)
    at Socket.socketErrorListener (_http_client.js:401:9)
    at Socket.emit (events.js:198:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at process._tickCallback (internal/process/next_tick.js:63:19), errno=ENOTFOUND, code=ENOTFOUND, syscall=getaddrinfo, hostname=ca.m-rphxyxdr2zeqljyk6aev5d5txm.n-dzlj7f7bpzed7kwkyi6sdlofxa.managedblockchain.us-east-1.amazonaws.com, host=ca.m-rphxyxdr2zeqljyk6aev5d5txm.n-dzlj7f7bpzed7kwkyi6sdlofxa.managedblockchain.us-east-1.amazonaws.com, port=30002
Failed to enroll admin user "admin": Error: Calling enroll endpoint failed with error [Error: getaddrinfo ENOTFOUND ca.m-rphxyxdr2zeqljyk6aev5d5txm.n-dzlj7f7bpzed7kwkyi6sdlofxa.managedblockchain.us-east-1.amazonaws.com ca.m-rphxyxdr2zeqljyk6aev5d5txm.n-dzlj7f7bpzed7kwkyi6sdlofxa.managedblockchain.us-east-1.amazonaws.com:30002]

**Comment by Nizomjon1994** [comment]
Hyperledger connection-profile : ~/blockchain-explorer/app/platform/fabric/connection-profile/first-network.json

{
  "name": "first-network",
  "version": "1.0.0",
  "client": {
    "tlsEnable": true,
    "adminCredential": {
      "id": "admin",
      "password": "Adminpwd1!"
    },
    "caCredential": {
      "id": "admin",
      "password": "Adminpwd1!"
    },
    "enableAuthentication": true,
    "organization": "Org1",
    "connection": {
      "timeout": {
        "peer": {
          "endorser": "300"
        },
        "orderer": "300"
      }
    }
  },
  "channels": {
    "mychannel": {
      "orderers": [
        "orderer.com"
      ],
      "peers": {
        "peer1": {
          "endorsingPeer": true,
          "chaincodeQuery": true,
          "ledgerQuery": true,
          "eventSource": true
        }
      },
      "connection": {
        "timeout": {
          "peer": {
            "endorser": "6000",
            "eventHub": "6000",
            "eventReg": "6000"
          }
        }
      }
    }
  },
  "organizations": {
    "Org1": {
      "mspid": "m-RPHXYXDR2ZEQLJYK6AEV5D5TXM",
      "peers": [
        "peer1"
      ],
      "certificateAuthorities": [
        "ca-org1"
      ],
      "adminPrivateKey": {
        "path": "/home/explore/ec116e84c3f662bad893dd93f0e6eefc83dcbc9a1b77ca2ac7968f3e1a4dd536_sk"
      },
      "signedCert": {
        "path": "/tmp/admin-msp/signcerts/cert.pem"
      }
    }
  },
  "peers": {
    "peer1": {
      "url": "grpcs://nd-e7lcbbalprb2xeerzvf33iiaii.m-rphxyxdr2zeqljyk6aev5d5txm.n-dzlj7f7bpzed7kwkyi6sdlofxa.managedblockchain.us-east-1.amazonaws.com:30003",
      "grpcOptions": {
        "ssl-target-name-override": "nd-e7lcbbalprb2xeerzvf33iiaii.m-rphxyxdr2zeqljyk6aev5d5txm.n-dzlj7f7bpzed7kwkyi6sdlofxa.managedblockchain.us-east-1.amazonaws.com"
      },
      "tlsCACerts": {
        "path": "/home/explorer/managedblockchain-tls-chain.pem"
      }
    }
  },
  "certificateAuthorities": {
    "ca-org1": {
      "url": "https://ca.m-rphxyxdr2zeqljyk6aev5d5txm.n-dzlj7f7bpzed7kwkyi6sdlofxa.managedblockchain.us-east-1.amazonaws.com:30002",
      "httpOptions": {
        "verify": false
      },
      "tlsCACerts": {
        "path": "/home/explorer/ca-m-rphxyxdr2zeqljyk6aev5d5txm-n-dzlj7f7bpzed7kwkyi6sdlofxa-managedblockchain-us-east-1-amazonaws-com-30002.pem"
      },
      "caName": "m-RPHXYXDR2ZEQLJYK6AEV5D5TXM",
      "registrar": {
        "enrollId": "admin",
        "enrollSecret": "Adminpwd1!"
      }
    }
  }
}
