### ISSUE TITLE
Part 4 - Problem starting Angular.js app

### ISSUE THREAD

**Issue by jackchi** [aws-samples/non-profit-blockchain#37]
Everything was going great until the REST app where first in Part 3, the curl command failed with:
`
[2019-07-25T23:43:31.176] [ERROR] NGOAPI - ##### POST on Users - Failed to register the username michael for organization Org1 with::failed Error: Enrollment failed with errors [[{"code":20,"message":"Authorization failure"}]]
[2019-07-25T23:43:34.274] [INFO] NGOAPI -  ##### New request for URL /health
[2019-07-25T23:43:39.674] [INFO] NGOAPI - ##### dummySpend GET on Donation - username : michael
[2019-07-25T23:43:39.674] [INFO] NGOAPI - ##### dummySpend GET on Donation - userOrg : Org1
[2019-07-25T23:43:39.674] [INFO] NGOAPI - ##### dummySpend GET on Donation - channelName : mychannel
[2019-07-25T23:43:39.674] [INFO] NGOAPI - ##### dummySpend GET on Donation - chaincodeName : ngo
[2019-07-25T23:43:39.674] [INFO] NGOAPI - ##### dummySpend GET on Donation - fcn : queryAllDonations
[2019-07-25T23:43:39.674] [INFO] NGOAPI - ##### dummySpend GET on Donation - args : {}
[2019-07-25T23:43:39.675] [INFO] NGOAPI - ##### dummySpend GET on Donation - peers : peer1
[2019-07-25T23:43:39.675] [INFO] Connection - ============ START getClientForOrg for org Org1 and user michael
`

On the REST API App:
`[2019-07-25T23:43:31.176] [ERROR] Connection - ##### getRegisteredUser - Failed to get registered user: michael with error: Error: Enrollment failed with errors [[{"code":20,"message":"Authorization failure"}]]`

Then in Part 4 in npm start on ngo-ui

`[ec2-user@ip-10-0-156-129 ngo-ui]$ npm start &
[ec2-user@ip-10-0-156-129 ngo-ui]$ 
ngo-blockchain@0.0.0 start /home/ec2-user/non-profit-blockchain/ngo-ui
ng serve --host 0.0.0.0 --port 8080 --disableHostCheck
Schema validation failed with the following errors:
  Data path ".builders['app-shell']" should have required property 'class'.
Error: Schema validation failed with the following errors:
  Data path ".builders['app-shell']" should have required property 'class'.
    at MergeMapSubscriber._registry.compile.pipe.operators_1.concatMap.validatorResult [as project] (/home/ec2-user/non-profit-blockchain/ngo-ui/node_modules/@angular-devkit/core/src/workspace/workspace.js:215:42)
    at MergeMapSubscriber._tryNext (/home/ec2-user/non-profit-blockchain/ngo-ui/node_modules/@angular-devkit/core/node_modules/rxjs/internal/operators/mergeMap.js:69:27)
    at MergeMapSubscriber._next (/home/ec2-user/non-profit-blockchain/ngo-ui/node_modules/@angular-devkit/core/node_modules/rxjs/internal/operators/mergeMap.js:59:18)
    at MergeMapSubscriber.Subscriber.next (/home/ec2-user/non-profit-blockchain/ngo-ui/node_modules/@angular-devkit/core/node_modules/rxjs/internal/Subscriber.js:67:18)
    at MergeMapSubscriber.notifyNext (/home/ec2-user/non-profit-blockchain/ngo-ui/node_modules/@angular-devkit/core/node_modules/rxjs/internal/operators/mergeMap.js:92:26)
    at InnerSubscriber._next (/home/ec2-user/non-profit-blockchain/ngo-ui/node_modules/@angular-devkit/core/node_modules/rxjs/internal/InnerSubscriber.js:28:21)
    at InnerSubscriber.Subscriber.next (/home/ec2-user/non-profit-blockchain/ngo-ui/node_modules/@angular-devkit/core/node_modules/rxjs/internal/Subscriber.js:67:18)
    at MapSubscriber._next (/home/ec2-user/non-profit-blockchain/ngo-ui/node_modules/@angular-devkit/core/node_modules/rxjs/internal/operators/map.js:55:26)
    at MapSubscriber.Subscriber.next (/home/ec2-user/non-profit-blockchain/ngo-ui/node_modules/@angular-devkit/core/node_modules/rxjs/internal/Subscriber.js:67:18)
    at SwitchMapSubscriber.notifyNext (/home/ec2-user/non-profit-blockchain/ngo-ui/node_modules/@angular-devkit/core/node_modules/rxjs/internal/operators/switchMap.js:86:26)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ngo-blockchain@0.0.0 start: `ng serve --host 0.0.0.0 --port 8080 --disableHostCheck`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ngo-blockchain@0.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ec2-user/.npm/_logs/2019-07-25T23_29_49_177Z-debug.log`

Not sure if anybody else has encountered this? Btw - this is super great guide with video. Thanks for doing this.

**Comment by jitrani** [comment]
you are getting any solutions?

**Comment by MCLDG** [comment]
I suspect the "Authorization failure" in the REST API is caused by an incorrect admin username or password in config.json
