### ISSUE TITLE
Trying to run the user interface

### ISSUE THREAD

**Issue by yangricardo** [aws-samples/non-profit-blockchain#59]
Hi, i'm getting the following error after `npm start`:

Schema validation failed with the following errors:
  Data path ".builders['app-shell']" should have required property 'class'.
Error: Schema validation failed with the following errors:
  Data path ".builders['app-shell']" should have required property 'class'.
    at MergeMapSubscriber._registry.compile.pipe.operators_1.concatMap.validatorResult [as project] (/home/ec2-user/non-profit-blockchain/ngo-ui/node_modules/@angular-devkit/core/src/workspace/workspace.js:215:42)
    at MergeMapSubscriber._tryNext (/home/ec2-user/non-profit-blockchain/ngo-ui/node_modules/@angular-devkit/core/node_modules/rxjs/internal/operators/mergeMap.js:69:27)
    at MergeMapSubscriber._next (/home/ec2-user/non-profit-blockchain/ngo-ui/node_modules/@angular-devkit/core/node_modules/rxjs/internal/operators/mergeMap.js:59:18)
    at MergeMapSubscriber.Subscriber.next (/home/ec2-user/non-profit-blockchain/ngo-ui/node_modules/@angular-devkit/core/node_modules/rxjs/internal/Subscriber.js:67:18)
    at MergeMapSubscriber.notifyNext (/home/ec2-user/non-profit-blockchain/ngo-ui/node_modules/@angular-devkit/core/node_modules/rxjs/internal/operators/mergeMap.js:92:26)
    at InnerSubscriber._next (/home/ec2-user/non-profit-blockchain/ngo-ui/node_modules/@angular-devkit/core/node_modules/rxjs/internal/InnerSubscriber.js:28:21)
    at InnerSubscriber.Subscriber.next (/home/ec2-user/non-profit-blockchain/ngo-ui/node_modules/@angular-devkit/core/node_modules/rxjs/internal/Subscriber.js:67:18)
    at MapSubscriber._next (/home/ec2-user/non-profit-blockchain/ngo-ui/node_modules/@angular-devkit/core/node_modules/rxjs/internal/operators/map.js:55:26)
    at MapSubscriber.Subscriber.next (/home/ec2-user/non-profit-blockchain/ngo-ui/node_modules/@angular-devkit/core/node_modules/rxjs/internal/Subscriber.js:67:18)
    at SwitchMapSubscriber.notifyNext (/home/ec2-user/non-profit-blockchain/ngo-ui/node_modules/@angular-devkit/core/node_modules/rxjs/internal/operators/switchMap.js:86:26)
    at InnerSubscriber._next (/home/ec2-user/non-profit-blockchain/ngo-ui/node_modules/@angular-devkit/core/node_modules/rxjs/internal/InnerSubscriber.js:28:21)
    at InnerSubscriber.Subscriber.next (/home/ec2-user/non-profit-blockchain/ngo-ui/node_modules/@angular-devkit/core/node_modules/rxjs/internal/Subscriber.js:67:18)
    at /home/ec2-user/non-profit-blockchain/ngo-ui/node_modules/@angular-devkit/core/node_modules/rxjs/internal/util/subscribeTo.js:17:28
    at Object.subscribeToResult (/home/ec2-user/non-profit-blockchain/ngo-ui/node_modules/@angular-devkit/core/node_modules/rxjs/internal/util/subscribeToResult.js:10:45)
    at SwitchMapSubscriber._innerSub (/home/ec2-user/non-profit-blockchain/ngo-ui/node_modules/@angular-devkit/core/node_modules/rxjs/internal/operators/switchMap.js:65:54)
    at SwitchMapSubscriber._next (/home/ec2-user/non-profit-blockchain/ngo-ui/node_modules/@angular-devkit/core/node_modules/rxjs/internal/operators/switchMap.js:55:14)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ngo-blockchain@0.0.0 start: `ng serve --host 0.0.0.0 --port 8080 --disableHostCheck`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ngo-blockchain@0.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ec2-user/.npm/_logs/2019-10-24T20_08_59_729Z-debug.log

i have tried another node version, and got the same error.

**Comment by MCLDG** [comment]
Could you try deleting the node_modules folder and rerunning all the instructions in Part 4. Just want to make sure you are using exactly the same version of Node and that you are installing it as per the instructions.
