### ISSUE TITLE
Error when attempting to start the application

### ISSUE THREAD

**Issue by sammi818881** [aws-samples/non-profit-blockchain#61]
When I attempt to run the node application from last Step-4 of Part-4, I'm getting the following error.  Any help would be much appreciated.  I've followed your steps to the letter, and this was the final step to get things up and running.

```
cloud9-ide-admin:~/non-profit-blockchain/ngo-ui (master) $ 
> ngo-blockchain@0.0.0 start /home/ec2-user/non-profit-blockchain/ngo-ui
> ng serve --host 0.0.0.0 --port 8080 --disableHostCheck

Schema validation failed with the following errors:
  Data path ".builders['app-shell']" should have required property 'class'.
Error: Schema validation failed with the following errors:
  Data path ".builders['app-shell']" should have required property 'class'.
    at MergeMapSubscriber._registry.compile.pipe.operators_1.concatMap.validatorResult [as project] (/home/ec2-user/non-profit-blockchain/ngo-ui/node_modules/@angular-devkit/core/src/workspace/workspace.js:215:42)
    at MergeMapSubscriber._tryNext (/home/ec2-user/non-profit-blockchain/ngo-ui/node_modules/@angular-devkit/core/node_modules/rxjs/internal/operators/mergeMap.js:69:27)
    at MergeMapSubscriber._next (/home/ec2-user/non-profit-blockchain/ngo-ui/node_modules/@angular-devkit/core/node_modules/rxjs/internal/operators/mergeMap.js:59:18)
    at MergeMapSubscriber.Subscriber.next (/home/ec2-user/non-profit-blockchain/ngo-ui/node_modules/@angular-devkit/core/node_modules/rxjs/internal/Subscriber.js:67:18)
    at MergeMapSubscriber.notifyNext (/home/ec2-user/non-profit-blockchain/ngo-ui/node_modules/@angular-devkit/core/node_modules/rxjs/internal/operators/mergeMap.js:92:26)
    at InnerSubscriber._next (/home/ec2-user/non-profit-blockchain/ngo-ui/node_modules/@angular-devkit/core/node_modules/rxjs/internal/InnerSubscriber.js:28:21)
    at InnerSubscriber.Subscriber.next (/home/ec2-user/non-profit-blockchain/ngo-ui/node_modules/@angular-devkit/core/node_modules/rxjs/internal/Subscriber.js:67:18)
    at MapSubscriber._next (/home/ec2-user/non-profit-blockchain/ngo-ui/node_modules/@angular-devkit/core/node_modules/rxjs/internal/operators/map.js:55:26)
    at MapSubscriber.Subscriber.next (/home/ec2-user/non-profit-blockchain/ngo-ui/node_modules/@angular-devkit/core/node_modules/rxjs/internal/Subscriber.js:67:18)
    at SwitchMapSubscriber.notifyNext (/home/ec2-user/non-profit-blockchain/ngo-ui/node_modules/@angular-devkit/core/node_modules/rxjs/internal/operators/switchMap.js:86:26)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ngo-blockchain@0.0.0 start: `ng serve --host 0.0.0.0 --port 8080 --disableHostCheck`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ngo-blockchain@0.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ec2-user/.npm/_logs/2019-11-10T14_49_16_727Z-debug.log
^C
[1]+  Exit 1                  npm start
cloud9-ide-admin:~/non-profit-blockchain/ngo-ui (master) $ node -v
v8.16.2
```

**Comment by MCLDG** [comment]
Hi @sammi818881 , it's difficult to debug the cause from the error message. Could you try part 4 again? I'm going to run through the workshop again this week and double check it all works.
